all_joints:
- [0]
- [1]
- [2]
- [3]
- [4]
- [5]
- [6]
- [7]
- [8]
- [9]
- [10]
- [11]
- [12]
- [13]
- [14]
- [15]
- [16]
- [17]
- [18]
- [19]
- [20]
- [21]
- [22]
- [23]
- [24]
all_joints_names: [Head, Pro, Meso, Meta, LF0, LF1, LF2, LM0, LM1, LM2, LH0, LH1,
  LH2, RF0, RF1, RF2, RM0, RM1, RM2, RH0, RH1, RH2, Bar, Axis, Fix]
batch_size: 1
cropratio: 0.4
dataset: training-datasets/iteration-0/UnaugmentedDataSet_CricketOct17/Cricket_Pranav95shuffle1.mat
dataset_type: imgaug
display_iters: 1000
global_scale: 0.8
init_weights: /usr/local/lib/python3.7/dist-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt
intermediate_supervision: false
intermediate_supervision_layer: 12
location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801
max_input_size: 1500
metadataset: training-datasets/iteration-0/UnaugmentedDataSet_CricketOct17/Documentation_data-Cricket_95shuffle1.pickle
min_input_size: 64
mirror: false
multi_step:
- [0.005, 10000]
- [0.02, 430000]
- [0.002, 730000]
- [0.001, 1030000]
net_type: resnet_50
num_joints: 25
pairwise_huber_loss: false
pairwise_predict: false
partaffinityfield_predict: false
pos_dist_thresh: 17
project_path: /content/drive/My Drive/Research/2.Cricket-Yuchen-2021-10-17
rotation: 25
rotratio: 0.4
save_iters: 50000
scale_jitter_lo: 0.5
scale_jitter_up: 1.25
